server:
  port: 8081
logging:
  level:
    root: debug
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
        - id: bill_manager
          uri: http://localhost:8082
          predicates:
            - Path=/**
          cors-configurations: